version: 2.1
orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2
jobs:
  build-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd frontend && npm i && npm run build
  test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd frontend && npm i && npm run test
  build-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:                
            - run: cd backend && npm i && npm run build
  test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend && npm i && npm run test
  analyze-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd frontend && npm audit fix --audit-level=critical --force
  analyze-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend && npm audit fix --audit-level=critical --force
  slack-notify:
    executor:
      name: node/default
    steps:
      - run: exit 0
      - slack/status:
          fail_only: true
          mentions: 'dtosidis'
          only_for_branches: only_for_branches
          webhook: https://app.slack.com/client/T013H39SHNE/
        #          channel: https://app.slack.com/client/T013H39SHNE
        #  color: '#42e2f4'
        #  mentions: 'dtosidis'
        #  message: This is a custom message notification
        #  webhook: https://app.slack.com/client/T013H39SHNE/
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - checkout
            - "7c:6f:89:3f:8d:67:78:dd:00:49:52:3e:e5:d2:1c:3b"
workflows:
  build-and-test:
    jobs:
      - build-frontend
      - test-frontend:
         requires:
           - build-frontend
      - build-backend
      - test-backend:
         requires:
           - build-backend
      - analyze-frontend:
         requires:
           - test-frontend
      - analyze-backend:
         requires:
           - test-backend
      - slack-notify
