version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Lint frontend
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd frontend
      - run: npm install
      - run: npm run test
  build-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Lint backend        
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd backend
      - run: npm install
      - run: npm run test
  analyze-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit --audit-level=critical
  analyze-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit --audit-level=critical
workflows:
  build-and-test:
    jobs:
      - build-frontend
      - test-frontend:
         requires:
           - build-frontend
      - build-backend
      - test-backend:
         requires:
           - build-backend
      - analyze-frontend:
         requires:
           - test-frontend
      - analyze-backend:
         requires:
           - test-backend
